<a href="https://colab.research.google.com/github/nascimento-luciano/Artificial-Intelligence/blob/master/ProdutoDeVetores2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np #importa a biblioteca numpy com o apelido de np

M1 = np.array([[1,2], [3,4]]) #cria a matriz e guarda na variável "M1"
M2 = np.array([[1,0], [-1,2]]) #cria a matriz e guarda na variável "M2"

Mprod=M1*M2 #vprod será o produto termo a termo
Mdot=np.dot(M1,M2) #vdot será o produto escalar

print("M1*M2 =\n", Mprod) #mostra as matrizes resultantes das duas operações
print("M1.M2 =\n", Mdot)

Mquad1=M1**2 #eleva um np.array ao quadrado termo a termo
M3 = np.matrix([[1,2],[3,4]]) #cria a matriz na forma de np.matrix e guarda na variável "M3"

Mquad3=M3**2 #eleva uma np.matrix ao quadrado com o produto de matrizes

print("Mquad1==\n", Mquad1) #mostra as matrizes resultantes das duas operações de elevado
print("Mquad2==\n", Mquad3)

M1*M2 =
 [[ 1  0]
 [-3  8]]
M1.M2 =
 [[-1  4]
 [-1  8]]
Mquad1==
 [[ 1  4]
 [ 9 16]]
Mquad2==
 [[ 7 10]
 [15 22]]
